# Generated by Django 4.2.6 on 2023-10-26 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 1, 33, 8, 846850)),
        ),
    ]
