# Generated by Django 4.2.6 on 2023-10-26 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='base.question'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('text', 'id')},
        ),
    ]
