# Generated by Django 4.2.6 on 2023-10-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_choice_question_alter_choice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('text', 'question')},
        ),
    ]
