# Generated by Django 4.2.6 on 2023-10-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_choice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
    ]
