# Generated by Django 4.2.6 on 2023-10-26 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
    ]
