# Generated by Django 4.2.6 on 2023-10-26 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_submittedanswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedanswer',
            name='index',
        ),
        migrations.RemoveField(
            model_name='submittedanswer',
            name='text',
        ),
        migrations.AddField(
            model_name='submittedanswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='base.answer'),
        ),
    ]
