# Generated by Django 4.2.6 on 2023-10-26 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_submittedanswer_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.submittedanswer'),
        ),
    ]
