# Generated by Django 4.2.6 on 2023-10-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_answer_submitted_answer_answer_choice_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedanswer',
            name='question',
        ),
    ]
