# Generated by Django 4.2.6 on 2023-10-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_answer_answer_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
