# Generated by Django 4.2.6 on 2023-10-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_answer_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_answer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SA', 'Single Answer'), ('MA', 'Multi Answer')], max_length=2),
        ),
    ]
