# Generated by Django 4.2.6 on 2023-10-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_choice_index_alter_choice_is_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='index',
            field=models.IntegerField(),
        ),
    ]
