# Generated by Django 4.2.6 on 2023-10-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_delete_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedanswer',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
