# Generated by Django 4.2.6 on 2023-10-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_submittedanswer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
