# Generated by Django 4.2.6 on 2023-10-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_question_description_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
