# Generated by Django 4.2.6 on 2023-10-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_question_description_alter_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
